import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>

          <div className="nav">
            <div class="items-left">
              <a href="#">Work</a>
              <a href="#">Gallery</a>
            </div>
            <div class="items-left">
              <a href="#">About</a>
              <a href="#">Contact</a>
            </div>
          </div>
          <div class="logo-container">
            <img src="/img/mon-logo.svg" alt="mon. logo" />
          </div>
          <div class="container"></div>
          <div class="content">
            <img src="/img/page-break-eg.png" alt="page break eg" />
          </div>

        </main>

        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
