import dynamic from "next/dynamic";
import Head from "next/head";
import { useEffect } from "react";
import styles from "@/styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    async function loadGSAP() {
      const gsapModule = await import("gsap");
      const ScrollTriggerModule = await import("gsap/ScrollTrigger");

      const { default: gsap } = gsapModule;
      const { ScrollTrigger } = ScrollTriggerModule;

      gsap.registerPlugin(ScrollTrigger);

      ScrollTrigger.create({
        animation: gsap.from(".logo", {
          y: "50vh",
          scale: 8,
          yPercent: -50,
        }), 
          scrub: true,
          trigger: ".content",
          start: "top bottom",
          endTrigger: ".content",
          end: "top center",
      });
    }

    loadGSAP();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>

          <div className={styles.nav}>
            <div className={styles.items_left}>
              <a href="#">Work</a>
              <a href="#">Gallery</a>
            </div>
            <div className={styles.items_right}>
              <a href="#">About</a>
              <a href="#">Contact</a>
            </div>
          </div>

          <div className={styles.logo_container}>
            <img className={`${styles.logo} logo`}  src="/img/mon-logo.svg" alt="mon. logo" />
          </div>

          <div className={styles.container}></div>

          <div className={`${styles.content} content`}>
            <div>
              <h1>Xin chao 👋, I'm</h1>
              <img src="/img/landing/landing-monica-nguyen.svg" alt="monica nguyen" />
            </div>
          </div>

        </main>

        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
