import styles from "@/styles/Home.module.css";
import Head from "next/head";
import { useEffect } from "react";
import { gsap } from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

// Dynamically import GSAP and ScrollTrigger to avoid SSR issues
const gsap = dynamic(() => import("gsap"), { ssr: false });
const ScrollTrigger = dynamic(() => import("gsap/ScrollTrigger"), { ssr: false });

export default function Home() {
  useEffect(() => {
    Promise.all([gsap, ScrollTrigger]).then(([gsap, { ScrollTrigger }]) => {
      gsap.registerPlugin(ScrollTrigger);

      ScrollTrigger.create({
        animation: gsap.from(".logo", {
          y: "50vh",
          scale: 6,
          yPercent: -50,
        }),
        scrub: true,
        trigger: ".content",
        start: "top bottom",
        endTrigger: ".content",
        end: "top center",
      });
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>

          <div className={styles.nav}>
            <div className={styles.items_left}>
              <a href="#">Work</a>
              <a href="#">Gallery</a>
            </div>
            <div className={styles.items_right}>
              <a href="#">About</a>
              <a href="#">Contact</a>
            </div>
          </div>

          <div className={styles.logo_container}>
            <img className={styles.logo}  src="/img/mon-logo.svg" alt="mon. logo" />
          </div>

          <div className={styles.container}></div>

          <div className={styles.content}>
            <img src="/img/page-break-eg.png" alt="page break eg" />
          </div>

        </main>

        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
