import dynamic from "next/dynamic";
import Head from "next/head";
import { useEffect } from "react";
import styles from "@/styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    async function loadGSAP() {
      const gsapModule = await import("gsap");
      const ScrollTriggerModule = await import("gsap/ScrollTrigger");

      const { default: gsap } = gsapModule;
      const { ScrollTrigger } = ScrollTriggerModule;

      gsap.registerPlugin(ScrollTrigger);

      // Set the initial state of the logo (fullscreen size)
      gsap.set(".logo", {
        scale: 6,
        y: "50vh",
      });

      // Create the shrinking animation tied to scroll
      ScrollTrigger.create({
        trigger: ".content", // Trigger when `.content` enters the viewport
        start: "top top", // Animation starts when `.content` hits the top of the viewport
        end: "bottom top", // Animation ends when `.content` leaves the viewport
        scrub: true, // Makes the animation smooth and tied to scroll
        animation: gsap.to(".logo", {
          scale: -1, // Shrinks the logo to normal size
          y: 0, // Moves the logo to its final position
        }),
        markers: true, // Debug markers for start/end points
      });
    }

    loadGSAP();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>

          <div className={styles.nav}>
            <div className={styles.items_left}>
              <a href="#">Work</a>
              <a href="#">Gallery</a>
            </div>
            <div className={styles.items_right}>
              <a href="#">About</a>
              <a href="#">Contact</a>
            </div>
          </div>

          <div className={styles.logo_container}>
            <img className={`${styles.logo} logo`}  src="/img/mon-logo.svg" alt="mon. logo" />
          </div>

          <div className={styles.container}></div>

          <div className={styles.content}>
            <img src="/img/page-break-eg.png" alt="page break eg" />
          </div>

        </main>

        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
